# Generated by Django 6.0.1 on 2026-01-23 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0003_delete_tournee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heure_debut", models.DateTimeField(verbose_name="Heure de début")),
                (
                    "heure_fin",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Heure de fin"
                    ),
                ),
                (
                    "duree",
                    models.DurationField(blank=True, null=True, verbose_name="Durée"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournees",
                        to="authentication.agent",
                        verbose_name="Agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournée",
                "verbose_name_plural": "Tournées",
                "db_table": "tournees",
                "ordering": ["-heure_debut"],
            },
        ),
    ]
