# Generated by Django 6.0 on 2026-01-25 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournee",
            name="duree",
        ),
    ]
