# Generated by Django 6.0.1 on 2026-01-28 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0008_rename_idx_agent_statut_commandes_agent_i_e10ee1_idx_and_more",
        ),
        ("tours", "0003_add_commande_field"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="tournee",
            new_name="tournees_agent_i_3e65fa_idx",
            old_name="idx_tournee_agent",
        ),
        migrations.RenameIndex(
            model_name="tournee",
            new_name="tournees_command_323efd_idx",
            old_name="idx_tournee_commande",
        ),
        migrations.AlterField(
            model_name="tournee",
            name="commande",
            field=models.ForeignKey(
                help_text="Commande pour laquelle cette tournée est effectuée",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournees",
                to="orders.commande",
                verbose_name="Commande liée",
            ),
        ),
    ]
