# Generated by Django 6.0.1 on 2026-01-23 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heure_debut", models.DateTimeField()),
                ("heure_fin", models.DateTimeField(blank=True, null=True)),
                ("duree", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournees",
                        to="authentication.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournée",
                "verbose_name_plural": "Tournées",
                "db_table": "tournees",
                "ordering": ["-heure_debut"],
            },
        ),
    ]
