# Generated by Django 6.0.1 on 2026-01-23 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_tournee"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tournee",
        ),
    ]
