# Generated by Django 6.0.1 on 2026-01-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_delete_tournee"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("agent", "Agent"), ("client", "Client")],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "data",
                    models.JSONField(help_text="Données temporaires de l'utilisateur"),
                ),
                ("otp_code", models.CharField(max_length=6)),
                ("otp_expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Utilisateur en attente",
                "verbose_name_plural": "Utilisateurs en attente",
                "db_table": "pending_users",
            },
        ),
    ]
