# Generated by Django 6.0.1 on 2026-01-24 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_pendinguser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingUser",
        ),
    ]
