# Generated by Django 6.0.1 on 2026-01-24 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=8, max_digits=10, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=8, max_digits=11, verbose_name="Longitude"
                    ),
                ),
                (
                    "precision",
                    models.FloatField(
                        blank=True,
                        help_text="Précision de la localisation GPS en mètres",
                        null=True,
                        verbose_name="Précision (mètres)",
                    ),
                ),
                (
                    "vitesse",
                    models.FloatField(
                        blank=True,
                        help_text="Vitesse de déplacement en km/h",
                        null=True,
                        verbose_name="Vitesse (km/h)",
                    ),
                ),
                (
                    "altitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Altitude (mètres)"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="authentication.agent",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "tournee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="tours.tournee",
                        verbose_name="Tournée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position Agent",
                "verbose_name_plural": "Positions Agents",
                "db_table": "positions_agents",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["agent", "-timestamp"],
                        name="positions_a_agent_i_d49b58_idx",
                    ),
                    models.Index(
                        fields=["tournee", "-timestamp"],
                        name="positions_a_tournee_a5cd59_idx",
                    ),
                ],
            },
        ),
    ]
