# Generated by Django 6.0.1 on 2026-01-23 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0003_delete_tournee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_demandee",
                    models.IntegerField(verbose_name="Quantité demandée"),
                ),
                (
                    "date_livraison_souhaitee",
                    models.DateField(verbose_name="Date de livraison souhaitée"),
                ),
                (
                    "adresse_livraison",
                    models.TextField(verbose_name="Adresse de livraison"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("acceptee", "Acceptée"),
                            ("en_cours", "En cours de livraison"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "notes_client",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notes du client"
                    ),
                ),
                (
                    "notes_admin",
                    models.TextField(blank=True, null=True, verbose_name="Notes admin"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commandes",
                        to="authentication.agent",
                        verbose_name="Agent assigné",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="authentication.client",
                        verbose_name="Client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
                "db_table": "commandes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("nouvelle_commande", "Nouvelle commande"),
                            ("livraison_assignee", "Livraison assignée"),
                            ("livraison_terminee", "Livraison terminée"),
                            ("commande_annulee", "Commande annulée"),
                        ],
                        max_length=30,
                        verbose_name="Type de notification",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                ("lue", models.BooleanField(default=False, verbose_name="Lue")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="authentication.agent",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="authentication.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="orders.commande",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
