# Generated by Django 6.0.1 on 2026-01-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_commande_quantite_demandee_lignecommande"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="quantite_demandee",
            field=models.IntegerField(
                blank=True,
                help_text="Optionnel - calculé depuis les lignes",
                null=True,
                verbose_name="Quantité demandée",
            ),
        ),
    ]
