# Generated by Django 6.0 on 2026-01-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_commande_quantite_demandee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="quantite_demandee",
            field=models.IntegerField(
                blank=True,
                help_text="Optionnel - calculé depuis les lignes de commande",
                null=True,
                verbose_name="Quantité totale demandée",
            ),
        ),
        migrations.AlterField(
            model_name="lignecommande",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                verbose_name="Montant total (quantité × prix)",
            ),
        ),
        migrations.AlterField(
            model_name="lignecommande",
            name="prix_unitaire",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Prix capturé lors de la commande (peut différer du prix actuel)",
                max_digits=10,
                verbose_name="Prix unitaire au moment de la commande",
            ),
        ),
    ]
