# Generated by Django 6.0 on 2026-01-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_commande_quantite_demandee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="date_livraison_souhaitee",
        ),
        migrations.RemoveField(
            model_name="commande",
            name="notes_admin",
        ),
        migrations.RemoveField(
            model_name="commande",
            name="notes_client",
        ),
    ]
