# Generated by Django 6.0 on 2026-01-25 09:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_commande_date_livraison_souhaitee_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="adresse_livraison",
        ),
        migrations.AddField(
            model_name="commande",
            name="latitude_livraison",
            field=models.DecimalField(
                decimal_places=8,
                default=django.utils.timezone.now,
                help_text="Coordonnée GPS de la livraison (-90 à 90)",
                max_digits=10,
                verbose_name="Latitude du point de livraison",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="commande",
            name="longitude_livraison",
            field=models.DecimalField(
                decimal_places=8,
                default=django.utils.timezone.now,
                help_text="Coordonnée GPS de la livraison (-180 à 180)",
                max_digits=11,
                verbose_name="Longitude du point de livraison",
            ),
            preserve_default=False,
        ),
    ]
