# Generated by Django 6.0.1 on 2026-01-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("orders", "0007_add_unique_constraint"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="commande",
            new_name="commandes_agent_i_e10ee1_idx",
            old_name="idx_agent_statut",
        ),
        migrations.RenameIndex(
            model_name="commande",
            new_name="commandes_client__2fda5c_idx",
            old_name="idx_client_statut",
        ),
        migrations.AlterConstraint(
            model_name="commande",
            name="unique_agent_commande_active",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut__in", ["acceptee", "en_cours"])),
                fields=("agent",),
                name="unique_agent_commande_active",
            ),
        ),
    ]
