# Generated by Django 6.0.1 on 2026-01-23 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0003_delete_tournee"),
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=8, max_digits=10, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=8, max_digits=11, verbose_name="Longitude"
                    ),
                ),
                (
                    "quantite_livree",
                    models.IntegerField(verbose_name="Quantité livrée"),
                ),
                (
                    "montant_percu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant perçu (FCFA)",
                    ),
                ),
                ("date_livraison", models.DateField(verbose_name="Date de livraison")),
                (
                    "heure_livraison",
                    models.TimeField(verbose_name="Heure de livraison"),
                ),
                (
                    "duree_livraison",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Durée de la livraison"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("validee", "Validée"),
                            ("livree", "Livrée"),
                            ("annulee", "Annulée"),
                        ],
                        default="livree",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livraisons",
                        to="authentication.agent",
                        verbose_name="Agent",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livraisons",
                        to="authentication.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "tournee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livraisons",
                        to="tours.tournee",
                        verbose_name="Tournée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison",
                "verbose_name_plural": "Livraisons",
                "db_table": "livraisons",
                "ordering": ["-date_livraison", "-heure_livraison"],
            },
        ),
    ]
