# Generated by Django 6.0.1 on 2026-01-24 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livraison",
            name="montant_percu",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Montant perçu (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="livraison",
            name="quantite_livree",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Quantité livrée"
            ),
        ),
        migrations.CreateModel(
            name="LigneLivraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField(verbose_name="Quantité livrée")),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Prix unitaire au moment de la livraison",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant total (quantité × prix)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "livraison",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="deliveries.livraison",
                        verbose_name="Livraison",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_livraison",
                        to="products.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de livraison",
                "verbose_name_plural": "Lignes de livraison",
                "db_table": "lignes_livraison",
            },
        ),
    ]
