# Generated by Django 6.0.1 on 2026-01-24 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0002_alter_livraison_montant_percu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livraison",
            name="montant_percu",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optionnel - calculé depuis les lignes",
                max_digits=10,
                null=True,
                verbose_name="Montant perçu (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="livraison",
            name="quantite_livree",
            field=models.IntegerField(
                blank=True,
                help_text="Optionnel - calculé depuis les lignes",
                null=True,
                verbose_name="Quantité livrée",
            ),
        ),
    ]
