# Generated by Django 6.0 on 2026-01-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0003_alter_livraison_montant_percu_and_more"),
        ("orders", "0006_remove_commande_adresse_livraison_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignelivraison",
            name="ligne_commande",
            field=models.ForeignKey(
                blank=True,
                help_text="Ligne de commande correspondante (si livraison pour commande)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lignes_livraison",
                to="orders.lignecommande",
                verbose_name="Ligne de commande source",
            ),
        ),
        migrations.AddField(
            model_name="livraison",
            name="commande",
            field=models.ForeignKey(
                blank=True,
                help_text="Commande pour laquelle cette livraison est effectuée",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="livraisons",
                to="orders.commande",
                verbose_name="Commande associée",
            ),
        ),
    ]
