# Generated by Django 6.0.1 on 2026-01-24 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la catégorie"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="Image de la catégorie",
                    ),
                ),
                (
                    "ordre",
                    models.IntegerField(
                        default=0,
                        help_text="Ordre d'affichage dans l'app mobile (0 = premier)",
                        verbose_name="Ordre d'affichage",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(default=True, verbose_name="Catégorie active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "db_table": "categories",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom du produit"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "reference",
                    models.CharField(
                        help_text="Ex: VIT-500, VOL-1500",
                        max_length=50,
                        unique=True,
                        verbose_name="Référence produit",
                    ),
                ),
                (
                    "marque",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Vitale, Voltic, etc.",
                        max_length=100,
                        null=True,
                        verbose_name="Marque",
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 500ml, 1.5L, etc.",
                        max_length=50,
                        null=True,
                        verbose_name="Volume",
                    ),
                ),
                (
                    "unite_vente",
                    models.CharField(
                        choices=[
                            ("sachet", "Sachet"),
                            ("bouteille", "Bouteille"),
                            ("pack", "Pack"),
                            ("carton", "Carton"),
                        ],
                        default="sachet",
                        max_length=20,
                        verbose_name="Unité de vente",
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix de vente au détail",
                        max_digits=10,
                        verbose_name="Prix unitaire (FCFA)",
                    ),
                ),
                (
                    "prix_gros",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix pour les grossistes (optionnel)",
                        max_digits=10,
                        null=True,
                        verbose_name="Prix de gros (FCFA)",
                    ),
                ),
                (
                    "stock_minimum",
                    models.IntegerField(
                        default=0,
                        help_text="Alerte si stock en dessous",
                        verbose_name="Stock minimum",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="produits/",
                        verbose_name="Photo du produit",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(default=True, verbose_name="Produit actif"),
                ),
                (
                    "ordre",
                    models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produits",
                        to="products.categorie",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "db_table": "produits",
                "ordering": ["categorie", "ordre", "nom"],
                "indexes": [
                    models.Index(
                        fields=["categorie", "actif"],
                        name="produits_categor_0d4160_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="produits_referen_de09bd_idx"
                    ),
                ],
            },
        ),
    ]
