# Generated by Django 6.0 on 2026-01-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorie",
            options={
                "ordering": ["nom"],
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.AlterModelOptions(
            name="produit",
            options={
                "ordering": ["categorie", "marque", "nom"],
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
            },
        ),
        migrations.RemoveIndex(
            model_name="produit",
            name="produits_categor_0d4160_idx",
        ),
        migrations.RemoveIndex(
            model_name="produit",
            name="produits_referen_de09bd_idx",
        ),
        migrations.RemoveField(
            model_name="categorie",
            name="image",
        ),
        migrations.RemoveField(
            model_name="categorie",
            name="ordre",
        ),
        migrations.AlterUniqueTogether(
            name="produit",
            unique_together={("categorie", "nom", "volume")},
        ),
        migrations.AddField(
            model_name="produit",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Image du produit",
                null=True,
                upload_to="produits/",
                verbose_name="Photo du produit",
            ),
        ),
        migrations.AlterField(
            model_name="categorie",
            name="nom",
            field=models.CharField(
                help_text="Ex: Eau en sachet, Eau en bouteille, Boissons",
                max_length=100,
                unique=True,
                verbose_name="Nom de la catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="actif",
            field=models.BooleanField(
                default=True, verbose_name="Produit disponible à la vente"
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="marque",
            field=models.CharField(
                help_text="Ex: Vitale, Voltic, Coca-Cola, Fanta",
                max_length=100,
                verbose_name="Marque",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="nom",
            field=models.CharField(
                help_text="Ex: Eau Vitale, Eau Voltic, Coca-Cola",
                max_length=200,
                verbose_name="Nom du produit",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="prix_unitaire",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Prix de vente standard",
                max_digits=10,
                verbose_name="Prix unitaire (FCFA)",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="unite_vente",
            field=models.CharField(
                choices=[
                    ("sachet", "Sachet"),
                    ("bouteille", "Bouteille"),
                    ("canette", "Canette"),
                    ("pack", "Pack"),
                ],
                default="sachet",
                max_length=20,
                verbose_name="Unité de vente",
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="volume",
            field=models.CharField(
                blank=True,
                help_text="Ex: 500ml, 1.5L, 33cl",
                max_length=50,
                null=True,
                verbose_name="Volume/Contenance",
            ),
        ),
        migrations.RemoveField(
            model_name="produit",
            name="description",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="image",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="ordre",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="prix_gros",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="produit",
            name="stock_minimum",
        ),
    ]
